"""empty message

Revision ID: 7efbbbb842b4
Revises: 1fe9c62917b8
Create Date: 2019-11-11 03:06:29.698408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7efbbbb842b4'
down_revision = '1fe9c62917b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('lecture_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'lecture', ['lecture_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'lecture_id')
    # ### end Alembic commands ###
